version: "3.9"
services:
  server:
    build: { context: ./server, dockerfile: Dockerfile }
    ports: [ "5000:5000" ]
    env_file: [ ../.env ]
    volumes: [ "./server:/app" ]
    depends_on: [ mongo ]
  client:
    build: { context: ./client, dockerfile: Dockerfile }
    ports: [ "5173:5173" ]
    env_file: [ ../.env ]
    volumes: [ "./client:/app" ]
    command: ["npm","run","dev","--","--host"]
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: [ "27017:27017" ]
    volumes: [ "mongo_data:/data/db" ]
volumes: { mongo_data: {} }
